### PR TITLE
BROKER: Update Additional Details

### PR DESCRIPTION
**Pull request by rcruzfreelance**
Closes #[185](https://github.com/Mums-Who-Code/SCMS.Services/issues/185)

### CODE REVIEW

**Comment by ShriHumrudha** [comment]
Please update your branch.

**Review by ShriHumrudha — CHANGES_REQUESTED** [review]
Order the update after the 'SelectById'

**Comment by ShriHumrudha** [comment]
Are we missing the interface file?

**Comment by rcruzfreelance** [comment]
Missing methods for interfaces was added

**Review by ShriHumrudha — APPROVED** [review]

**Pull request merged**
