### PR TITLE
MEDIUM FIX: Extend Student Validation Tests for more attributes

### PR DESCRIPTION
**Pull request by rcruzfreelance**
Closes [#103](https://github.com/Mums-Who-Code/SCMS.Services/issues/103)

### CODE REVIEW

**Comment by ShriHumrudha** [comment]
> Closes [#103](https://github.com/Mums-Who-Code/SCMS.Services/issues/103)

There are few more test required. So please consider that and this would be medium fix.

**Comment by rcruzfreelance** [comment]
Could you please specify what kind of validation tests we need beside the one from the issue?

Date Of Birth - Value is required
Status - Value is invalid
CreatedDate - Date is required
CreatedBy - Id is required
Gender - Invalid & Not recognized

All of these test were validated in the test except the DateOfBrith

**Comment by ShriHumrudha** [comment]
> Could you please specify what kind of validation tests we need beside the one from the issue?
> 
> Date Of Birth - Value is required Status - Value is invalid CreatedDate - Date is required CreatedBy - Id is required Gender - Invalid & Not recognized
> 
> All of these test were validated in the test except the DateOfBrith

The pending ones are:
Status - Handle an undefined enum
Gender - Handle an undefined enum

**Comment by ShriHumrudha** [comment]
Closing due to inactivity

**Pull request closed without merging**
